name: Branch Based CI

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: "Select target branch"
        required: true
        default: "hello-world"
        type: choice
        options:
          - hello-world
          - math-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout selected branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.target_branch }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install pytest
        run: pip install pytest

      - name: Detect branch files
        run: |
          BRANCH="${{ github.event.inputs.target_branch }}"

          echo "Current branch: $BRANCH"

          if [ "$BRANCH" = "hello-world" ]; then
            echo "PROGRAM=hello.py" >> $GITHUB_ENV
            echo "TESTFILE=test_hello.py" >> $GITHUB_ENV

          elif [ "$BRANCH" = "math-app" ]; then
            echo "PROGRAM=math_app.py" >> $GITHUB_ENV
            echo "TESTFILE=test_math.py" >> $GITHUB_ENV

          else
            echo "Unknown branch"
            exit 1
          fi

      - name: Run Program
        run: python $PROGRAM

      - name: Run Tests
        run: pytest $TESTFILE -v
